# Load Lab Data
All data from lab are pre-stored in class `LocalLab`, call it with `.data`

In [19]:
from utilities.dataloader import LocalLab, LocalChopchop
from sklearn.model_selection import train_test_split

seed = 546

# load lab dataset
lab = LocalLab('data/danrer11_guide_results.txt')

lab.data.to_csv("data/danrer11_lab_all.csv")

X_train, X_test = train_test_split(lab.data, test_size=0.2,random_state = seed)
X_train.to_csv("data/danrer11_lab_train.csv")
X_test.to_csv("data/danrer11_lab_test.csv")

In [20]:
lab.data.head(10)

,GUIDE,qPCR,CONTROL,CHR,STRAND,TSS,LOCATION
0,GTGCCAAGTATAATGAGGAATGG,2.336301,1.074082,5,1,33339840,33339761
1,TGTAGCATAGTCGTGTTTGGAGG,4.897509,1.074082,5,-1,33339840,33339816
2,CCAAGTGAGACTTCGGAAAAAGG,2.432883,1.074082,5,1,33339840,33339954
3,GAATGTGTATAAATCAGGCTTGG,0.196000,1.335000,1,1,6225526,6226109
4,CTCTGAAATCCACATCACCGTGG,-0.341000,1.335000,1,1,6225526,6226147
5,GTCACATTTCCACGGTGATGTGG,-0.407000,1.335000,1,-1,6225526,6226156
6,AACAGAACTAATGCATTACGAGG,-0.200000,2.830000,12,-1,19958944,19959028
7,GCTTTTAACAGGACGAGACGAGG,0.090000,2.830000,12,-1,19958944,19959095
8,CTGATCACGGCTGAAGGACTCGG,-0.070000,2.830000,12,1,19958944,19959568
10,CCGCCGACAAAACCAACATGAGG,0.246900,1.816000,6,1,52675631,52675413

# Load Chopchop Data

In [21]:
chopchop = LocalChopchop("data/danrer11_chopchop.csv")

chopchop.data.to_csv("data/danrer11_chopchop_all.csv")

X_train, X_test = train_test_split(chopchop.data, test_size=0.2,random_state = seed)
X_train.to_csv("data/danrer11_chopchop_train.csv")
X_test.to_csv("data/danrer11_chopchop_test.csv")

In [22]:
chopchop.data.head(10)

                     GUIDE  EFFICIENCY  CHR  STRAND       TSS  LOCATION
0  CGATGTTGGGAAACTTGGGTAGG       70.94   10      -1  10016347  10016472
1  GATGAATGAGGAACGCGCAGCGG       64.36   10       1  10016347  10016403
2  TCAATTCATTATTCACGCGGAGG       59.94   10       1  10016347  10016437
3  ACGCGTCTTGAGCACTCGCTGGG       51.73   10       1  10016347  10016211
4  AAGATCGATGTTGGGAAACTTGG       38.63   10      -1  10016347  10016477
5  GACTCAAAAGCGCTACTTACTGG       35.21   10       1  10016347  10016261
6  CACGCGCACGGAGATGAATGAGG       63.35   10       1  10016347  10016391
7  AACCGCAGAAGATCGATGTTGGG       55.36   10      -1  10016347  10016485
8  TCTCCGTGCGCGTGAGTGAGAGG       55.23   10      -1  10016347  10016382
9  AGATCGATGTTGGGAAACTTGGG       54.79   10      -1  10016347  10016476